/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokenmgt;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Shahryar
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        Show_Products_In_JTable();
        ScreenCenter();
        look();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_search = new javax.swing.JLabel();
        txt_s = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_tuning = new javax.swing.JLabel();
        lbl_oilChange = new javax.swing.JLabel();
        lbl_repair = new javax.swing.JLabel();
        txt_foilchange = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_frepair = new javax.swing.JTextField();
        txt_ftunning = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_addname = new javax.swing.JLabel();
        lbl_addid = new javax.swing.JLabel();
        txt_addname = new javax.swing.JTextField();
        txt_addid = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_clr = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_delid = new javax.swing.JLabel();
        txt_delid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_delname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_deloil = new javax.swing.JTextField();
        txt_deltun = new javax.swing.JTextField();
        txt_delrep = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        btn_delclear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbl_search1 = new javax.swing.JLabel();
        txt_ups = new javax.swing.JTextField();
        lbl_name1 = new javax.swing.JLabel();
        lbl_tuning1 = new javax.swing.JLabel();
        lbl_oilChange1 = new javax.swing.JLabel();
        lbl_repair1 = new javax.swing.JLabel();
        txt_upoilchange = new javax.swing.JTextField();
        txt_upname = new javax.swing.JTextField();
        txt_uprepair = new javax.swing.JTextField();
        txt_uptunning = new javax.swing.JTextField();
        btn_upsearch = new javax.swing.JButton();
        btn_chg_oil1 = new javax.swing.JButton();
        btn_chg_tunning1 = new javax.swing.JButton();
        btn_chg_repair1 = new javax.swing.JButton();
        btn_clear1 = new javax.swing.JButton();
        btn_chg_name1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_upid = new javax.swing.JTextField();
        btn_chg_id = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        btn_exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Token Managment System");
        setResizable(false);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPane1.setName("Table"); // NOI18N

        jPanel1.setLayout(null);

        lbl_search.setText("Enter ID:");
        jPanel1.add(lbl_search);
        lbl_search.setBounds(15, 64, 70, 26);

        txt_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sActionPerformed(evt);
            }
        });
        jPanel1.add(txt_s);
        txt_s.setBounds(117, 64, 161, 26);

        lbl_name.setText("Name:");
        jPanel1.add(lbl_name);
        lbl_name.setBounds(15, 134, 47, 20);

        lbl_tuning.setText("Tunning:");
        jPanel1.add(lbl_tuning);
        lbl_tuning.setBounds(15, 220, 65, 20);

        lbl_oilChange.setText("Oil Change:");
        jPanel1.add(lbl_oilChange);
        lbl_oilChange.setBounds(15, 172, 84, 20);

        lbl_repair.setText("Repair:");
        jPanel1.add(lbl_repair);
        lbl_repair.setBounds(15, 263, 51, 20);

        txt_foilchange.setEditable(false);
        txt_foilchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_foilchangeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_foilchange);
        txt_foilchange.setBounds(117, 173, 161, 26);

        txt_fname.setEditable(false);
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fname);
        txt_fname.setBounds(117, 131, 161, 26);

        txt_frepair.setEditable(false);
        txt_frepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_frepairActionPerformed(evt);
            }
        });
        jPanel1.add(txt_frepair);
        txt_frepair.setBounds(117, 260, 161, 26);

        txt_ftunning.setEditable(false);
        txt_ftunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ftunningActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ftunning);
        txt_ftunning.setBounds(117, 217, 161, 26);

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search);
        btn_search.setBounds(300, 60, 79, 29);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(210, 300, 93, 29);

        jTabbedPane1.addTab("Find", jPanel1);

        lbl_addname.setText("Enter Name:");

        lbl_addid.setText("Enter ID: ");

        btn_add.setText("Add Customer");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_clr.setText("Clear");
        btn_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_addname)
                            .addComponent(lbl_addid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_addid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_addname, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_add))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_clr, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_addname)
                    .addComponent(txt_addname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_addid)
                    .addComponent(txt_addid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clr)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel2);

        lbl_delid.setText("Enter ID: ");

        txt_delid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_delidActionPerformed(evt);
            }
        });

        jLabel1.setText("Name: ");

        txt_delname.setEditable(false);
        txt_delname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_delnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Oil Change:");

        jLabel3.setText("Tunning:");

        jLabel4.setText("Repair:");

        txt_deloil.setEditable(false);
        txt_deloil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deloilActionPerformed(evt);
            }
        });

        txt_deltun.setEditable(false);

        txt_delrep.setEditable(false);
        txt_delrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_delrepActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_delclear.setText("Clear");
        btn_delclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_delid)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_delclear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_delid)
                        .addComponent(txt_delname)
                        .addComponent(txt_deloil, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(txt_deltun)
                        .addComponent(txt_delrep))
                    .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_delid)
                    .addComponent(txt_delid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_delname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_deloil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_deltun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_delrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_delclear))
        );

        jTabbedPane1.addTab("Delete", jPanel4);

        lbl_search1.setText("Enter ID:");

        txt_ups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upsActionPerformed(evt);
            }
        });

        lbl_name1.setText("Name:");

        lbl_tuning1.setText("Tunning:");

        lbl_oilChange1.setText("Oil Change:");

        lbl_repair1.setText("Repair:");

        txt_upoilchange.setEditable(false);
        txt_upoilchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upoilchangeActionPerformed(evt);
            }
        });

        txt_upname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upnameActionPerformed(evt);
            }
        });

        txt_uprepair.setEditable(false);
        txt_uprepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uprepairActionPerformed(evt);
            }
        });

        txt_uptunning.setEditable(false);
        txt_uptunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uptunningActionPerformed(evt);
            }
        });

        btn_upsearch.setText("Search");
        btn_upsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upsearchActionPerformed(evt);
            }
        });

        btn_chg_oil1.setText("Change");
        btn_chg_oil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chg_oil1ActionPerformed(evt);
            }
        });

        btn_chg_tunning1.setText("Change");
        btn_chg_tunning1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chg_tunning1ActionPerformed(evt);
            }
        });

        btn_chg_repair1.setText("Change");
        btn_chg_repair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chg_repair1ActionPerformed(evt);
            }
        });

        btn_clear1.setText("Clear");
        btn_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear1ActionPerformed(evt);
            }
        });

        btn_chg_name1.setText("Update Name");
        btn_chg_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chg_name1ActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        txt_upid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upidActionPerformed(evt);
            }
        });

        btn_chg_id.setText("Update ID");
        btn_chg_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chg_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lbl_name1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_upname, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txt_upid))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_chg_id)
                            .addComponent(btn_chg_name1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbl_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_ups, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_upsearch))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_oilChange1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_upoilchange, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btn_chg_oil1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_tuning1)
                        .addGap(37, 37, 37)
                        .addComponent(txt_uptunning, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btn_chg_tunning1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_repair1)
                        .addGap(51, 51, 51)
                        .addComponent(txt_uprepair, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btn_chg_repair1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btn_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_ups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_upsearch)))
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_upid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chg_id)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_name1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_upname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_chg_name1))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_oilChange1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_upoilchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_chg_oil1))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_tuning1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txt_uptunning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_chg_tunning1))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_repair1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_uprepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_chg_repair1))
                .addGap(14, 14, 14)
                .addComponent(btn_clear1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Update", jPanel5);

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Oil Change", "Tunning", "Repair"
            }
        ));
        tbl_data.setRowHeight(40);
        tbl_data.setRowMargin(3);
        jScrollPane1.setViewportView(tbl_data);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Database", jPanel3);

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel6.setText("CUSTOMER TOKENS MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Database");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection getConnection()
    {
         Connection con=null;
        String driver = "net.ucanaccess.jdbc.UcanaccessDriver";
        String url = "jdbc:ucanaccess://C:\\Users\\Shahryar\\Documents\\MS ACCESS\\customer.accdb";
        try{
           
            Class.forName(driver);
            con = DriverManager.getConnection(url);
            
            
        }catch(Exception ex )
        {
           System.out.println("Error"+ex);
        }
        return con;
    }
    
    
   public ArrayList<TokenMgt> getProductList()
    {
            ArrayList<TokenMgt> productList = new ArrayList<TokenMgt>();
            Connection con = getConnection();
            String query ="SELECT * FROM Company";
            Statement st;
            ResultSet rs;
        try {
            
            st = con.createStatement();
            rs= st.executeQuery(query);
            TokenMgt product;
            
            while(rs.next())
            {
                product = new TokenMgt(rs.getString("cus_ID"),rs.getString("cus_Name"),rs.getString("OilChange"),rs.getString("Tunning"),rs.getString("Repair"));
                productList.add(product);
            }
            
        } catch (SQLException ex) {
         
        }
        
        return productList;
        
        
    }
   
  
    public void Show_Products_In_JTable()
    {
        ArrayList<TokenMgt> list = getProductList();
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i=0; i<list.size();i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getoil();
            row[3] = list.get(i).gettun();
            row[4] = list.get(i).getrep();
            
            model.addRow(row);
        }
        
    }
  
   
     public void ScreenCenter()
   {
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
   }
   public void look()
   {
       UIManager.LookAndFeelInfo looks[];
       looks = UIManager.getInstalledLookAndFeels();
       try{
        UIManager.setLookAndFeel(looks[3].getClassName());
        SwingUtilities.updateComponentTreeUI(this);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Look:"+ex);
       }
     
       tbl_data.setDefaultRenderer(Object.class, new CustomTableCellRenderer());
    
       
   }
   
    
    
    
    
    private void txt_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sActionPerformed
       Connection con = getConnection();
        try
        {
             ResultSet rs=null;
             PreparedStatement ps;
       
        ps = con.prepareStatement("SELECT * FROM Company WHERE cus_ID=?");
        ps.setString(1, txt_s.getText());
        rs = ps.executeQuery();
        
      
      if(rs.next())
      {
          
        do 
        {
            
            txt_fname.setText(rs.getString("cus_Name"));
            if(rs.getString("OilChange").equals("TRUE"))
            {
                 txt_foilchange.setText("Consumed");
                 txt_foilchange.setBackground(Color.red);
                 
            }else if(rs.getString("OilChange").equals("FALSE"))
            {
                txt_foilchange.setText("FREE");
                txt_foilchange.setBackground(Color.green);
            }
            
            
             if(rs.getString("Tunning").equals("TRUE"))
            {
                 txt_ftunning.setText("Consumed");
                 txt_ftunning.setBackground(Color.red);
                 
            }else if(rs.getString("Tunning").equals("FALSE"))
            {
                txt_ftunning.setText("FREE");
                txt_ftunning.setBackground(Color.GREEN);
            }
            
           
            if(rs.getString("Repair").equals("TRUE"))
            {
                 txt_frepair.setText("Consumed");
                 txt_frepair.setBackground(Color.red);
            }else if(rs.getString("Repair").equals("FALSE"))
            {
                txt_frepair.setText("FREE");
                txt_frepair.setBackground(Color.GREEN);
            }
           
        }while(rs.next());
      }else
      {
           JOptionPane.showMessageDialog(null,"Customer Record Not Found");
      }
        
    
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,"Search:"+ex);
        }
        
        
    }//GEN-LAST:event_txt_sActionPerformed

    private void txt_foilchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_foilchangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foilchangeActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_frepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_frepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_frepairActionPerformed

    private void txt_ftunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ftunningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ftunningActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
         Connection con = getConnection();
         
         
         if(txt_s.getText().length()==0)
         {
             JOptionPane.showMessageDialog(null, "Enter Customer ID ");
         }
         else{
        try
        {
             ResultSet rs=null;
             PreparedStatement ps;
       
        ps = con.prepareStatement("SELECT * FROM Company WHERE cus_ID=?");
        ps.setString(1, txt_s.getText());
        rs = ps.executeQuery();
        
      
      if(rs.next())
      {
          
        do 
        {
            
            txt_fname.setText(rs.getString("cus_Name"));
            if(rs.getString("OilChange").equals("TRUE"))
            {
                 txt_foilchange.setText("Consumed");
                 txt_foilchange.setBackground(Color.red);
                 
            }else if(rs.getString("OilChange").equals("FALSE"))
            {
                txt_foilchange.setText("FREE");
                txt_foilchange.setBackground(Color.green);
            }
            
            
             if(rs.getString("Tunning").equals("TRUE"))
            {
                 txt_ftunning.setText("Consumed");
                 txt_ftunning.setBackground(Color.red);
                 
            }else if(rs.getString("Tunning").equals("FALSE"))
            {
                txt_ftunning.setText("FREE");
                txt_ftunning.setBackground(Color.GREEN);
            }
            
           
            if(rs.getString("Repair").equals("TRUE"))
            {
                 txt_frepair.setText("Consumed");
                 txt_frepair.setBackground(Color.red);
            }else if(rs.getString("Repair").equals("FALSE"))
            {
                txt_frepair.setText("FREE");
                txt_frepair.setBackground(Color.GREEN);
            }
           
        }while(rs.next());
      }else
      {
           JOptionPane.showMessageDialog(null,"Customer Record Not Found");
      }
        
    
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,"Search:"+ex);
        }
       }
        
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       
         Connection con = getConnection();
         int check = -1;
         
         if(txt_addname.getText().length()==0 && txt_addid.getText().length() ==0)
         {
             JOptionPane.showMessageDialog(null, "Enter ID or NAME Both");
         }
         else{
         
           try
        {
             ResultSet rs=null;
             PreparedStatement ps;
       
        ps = con.prepareStatement("INSERT INTO Company (cus_Name,cus_ID) VALUES(?,?)");
        ps.setString(1, txt_addname.getText());
        ps.setString(2, txt_addid.getText());
        check = ps.executeUpdate();
        
      if(check == 1)
      {
           JOptionPane.showMessageDialog(null," Add New Customer");
      }
        
        }catch(Exception ex)
        {
           
           JOptionPane.showMessageDialog(null,"Error: Can't Add New Customer");
      
          
       
        }}
           
      // tbl_data.repaint();
            Show_Products_In_JTable();
    }//GEN-LAST:event_btn_addActionPerformed

 public void windowClosing(WindowEvent e){
     String message = " Really Quit ? ";
                String title = "Quit";
       int result =JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

       if(result == JOptionPane.YES_OPTION){
               System.exit(0);
       }else{
               //Do nothing
       }
 }
    
    
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
       
                             String message = " Really Quit ? ";
                String title = "Quit";
                int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
       
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       txt_s.setText(null);
       txt_fname.setText(null);
       txt_foilchange.setText(null);
       txt_foilchange.setBackground(null);
       txt_ftunning.setText(null);
       txt_ftunning.setBackground(null);
       txt_frepair.setText(null);
       txt_frepair.setBackground(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clrActionPerformed
       txt_addname.setText(null);
       txt_addid.setText(null);
    }//GEN-LAST:event_btn_clrActionPerformed

    private void txt_delnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_delnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_delnameActionPerformed

    private void txt_deloilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deloilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deloilActionPerformed

    private void txt_delrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_delrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_delrepActionPerformed

    private void txt_delidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_delidActionPerformed
       
          Connection con = getConnection();
        try
        {
             ResultSet rs=null;
             PreparedStatement ps;
       
        ps = con.prepareStatement("SELECT * FROM Company WHERE cus_ID=?");
        ps.setString(1, txt_delid.getText());
        rs = ps.executeQuery();
        
      
      if(rs.next())
      {
          
        do 
        {
            
            txt_delname.setText(rs.getString("cus_Name"));
            if(rs.getString("OilChange").equals("TRUE"))
            {
                 txt_deloil.setText("Consumed");
                 txt_deloil.setBackground(Color.red);
                 
            }else if(rs.getString("OilChange").equals("FALSE"))
            {
                txt_deloil.setText("FREE");
                txt_deloil.setBackground(Color.green);
            }
            
            
             if(rs.getString("Tunning").equals("TRUE"))
            {
                 txt_deltun.setText("Consumed");
                 txt_deltun.setBackground(Color.red);
                 
            }else if(rs.getString("Tunning").equals("FALSE"))
            {
                txt_deltun.setText("FREE");
                txt_deltun.setBackground(Color.GREEN);
            }
            
           
            if(rs.getString("Repair").equals("TRUE"))
            {
                 txt_delrep.setText("Consumed");
                 txt_delrep.setBackground(Color.red);
            }else if(rs.getString("Repair").equals("FALSE"))
            {
                txt_delrep.setText("FREE");
                txt_delrep.setBackground(Color.GREEN);
            }
           
        }while(rs.next());
      }else
      {
           JOptionPane.showMessageDialog(null,"Customer Record Not Found");
      }
        
    
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,"Search:"+ex);
        }
        
        
        
    }//GEN-LAST:event_txt_delidActionPerformed

   
    
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
       
        Connection con = getConnection();
        int check=-1;
        String message = " You Want to DELETE "+txt_delname.getText()+" Record?";
        String title = "Delete";
        String id = txt_delid.getText();
       
        if(txt_delid.getText().length()==0)
        {
          JOptionPane.showMessageDialog(null, "Enter Customer ID");
        }else{
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {         
        try {
            PreparedStatement ps = con.prepareStatement("DELETE * FROM Company WHERE cus_ID=? ");
            ps.setString(1, id);
           check = ps.executeUpdate();
        } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null,"Delete:"+ex);
                     }
                }
        
        
        }
         Show_Products_In_JTable();
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_delclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delclearActionPerformed

       txt_delid.setText(null);
       txt_delname.setText(null);
       txt_deloil.setText(null);
       txt_deloil.setBackground(null);
       txt_deltun.setText(null);
       txt_deltun.setBackground(null);
       txt_delrep.setText(null);
       txt_delrep.setBackground(null);
        
    }//GEN-LAST:event_btn_delclearActionPerformed

    private void txt_upsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upsActionPerformed
       
          Connection con = getConnection();
         
         
         if(txt_ups.getText().length()==0)
         {
             JOptionPane.showMessageDialog(null, "Enter Customer ID ");
         }
         else{
        try
        {
             ResultSet rs=null;
             PreparedStatement ps;
       
        ps = con.prepareStatement("SELECT * FROM Company WHERE cus_ID=?");
        ps.setString(1, txt_ups.getText());
        rs = ps.executeQuery();
        
      
      if(rs.next())
      {
          
        do 
        {
            
            txt_upname.setText(rs.getString("cus_Name"));
            if(rs.getString("OilChange").equals("TRUE"))
            {
                 txt_upoilchange.setText("Consumed");
                 txt_upoilchange.setBackground(Color.red);
                 
            }else if(rs.getString("OilChange").equals("FALSE"))
            {
                txt_upoilchange.setText("FREE");
                txt_upoilchange.setBackground(Color.green);
            }
            
            
             if(rs.getString("Tunning").equals("TRUE"))
            {
                 txt_uptunning.setText("Consumed");
                 txt_uptunning.setBackground(Color.red);
                 
            }else if(rs.getString("Tunning").equals("FALSE"))
            {
                txt_uptunning.setText("FREE");
                txt_uptunning.setBackground(Color.GREEN);
            }
            
           
            if(rs.getString("Repair").equals("TRUE"))
            {
                 txt_uprepair.setText("Consumed");
                 txt_uprepair.setBackground(Color.red);
            }else if(rs.getString("Repair").equals("FALSE"))
            {
                txt_uprepair.setText("FREE");
                txt_uprepair.setBackground(Color.GREEN);
            }
           
        }while(rs.next());
      }else
      {
           JOptionPane.showMessageDialog(null,"Customer Record Not Found");
      }
        
    
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,"Search:"+ex);
        }
       }
         
        
    }//GEN-LAST:event_txt_upsActionPerformed

    private void txt_upoilchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upoilchangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_upoilchangeActionPerformed

    private void txt_upnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_upnameActionPerformed

    private void txt_uprepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uprepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uprepairActionPerformed

    private void txt_uptunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uptunningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uptunningActionPerformed

    private void btn_upsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upsearchActionPerformed
       
          Connection con = getConnection();
         
         
         if(txt_ups.getText().length()==0)
         {
             JOptionPane.showMessageDialog(null, "Enter Customer ID ");
         }
         else{
        try
        {
             ResultSet rs=null;
             PreparedStatement ps;
       
        ps = con.prepareStatement("SELECT * FROM Company WHERE cus_ID=?");
        ps.setString(1, txt_ups.getText());
        rs = ps.executeQuery();
        
      
      if(rs.next())
      {
          
        do 
        {
            
            txt_upname.setText(rs.getString("cus_Name"));
            if(rs.getString("OilChange").equals("TRUE"))
            {
                 txt_upoilchange.setText("Consumed");
                 txt_upoilchange.setBackground(Color.red);
                 
            }else if(rs.getString("OilChange").equals("FALSE"))
            {
                txt_upoilchange.setText("FREE");
                txt_upoilchange.setBackground(Color.green);
            }
            
            
             if(rs.getString("Tunning").equals("TRUE"))
            {
                 txt_uptunning.setText("Consumed");
                 txt_uptunning.setBackground(Color.red);
                 
            }else if(rs.getString("Tunning").equals("FALSE"))
            {
                txt_uptunning.setText("FREE");
                txt_uptunning.setBackground(Color.GREEN);
            }
            
           
            if(rs.getString("Repair").equals("TRUE"))
            {
                 txt_uprepair.setText("Consumed");
                 txt_uprepair.setBackground(Color.red);
            }else if(rs.getString("Repair").equals("FALSE"))
            {
                txt_uprepair.setText("FREE");
                txt_uprepair.setBackground(Color.GREEN);
            }
           
        }while(rs.next());
      }else
      {
           JOptionPane.showMessageDialog(null,"Customer Record Not Found");
      }
        
    
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,"Search:"+ex);
        }
       }
        
        
    }//GEN-LAST:event_btn_upsearchActionPerformed

    private void btn_chg_oil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chg_oil1ActionPerformed
        
        String str=null;
        String temp=null;
        
        if(txt_upoilchange.getText().equals("Consumed"))
        {
            temp = "TRUE";
        }else if(txt_upoilchange.getText().equals("FREE"))
        {
            temp = "FALSE";
        }
        
        
        
      //  str=txt_oilchange.getText();
        if(temp.equals("TRUE"))
        {
           txt_upoilchange.setText("FREE");
           txt_upoilchange.setBackground(Color.GREEN);
           temp = "FALSE";
            Connection con = getConnection();
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET OilChange = ? WHERE cus_ID = ?");
           ps.setString(1, temp );
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
         //  System.out.println(i);
            }catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(null,"OilChange:"+ex);
            }
       
        }else if(temp.equals("FALSE"))
        {
            txt_upoilchange.setText("Consumed");
            txt_upoilchange.setBackground(Color.red);
            temp = "TRUE";
            Connection con = getConnection();
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET OilChange = ? WHERE cus_ID = ?");
           ps.setString(1, temp);
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
        //   System.out.println(i);
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,"OilChange:"+ex);
            }
       
        }
      //  tbl_data.repaint();
         Show_Products_In_JTable();
        
    }//GEN-LAST:event_btn_chg_oil1ActionPerformed

    private void btn_chg_tunning1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chg_tunning1ActionPerformed
       
          String str=null;
         
         String temp=null;
        
        if(txt_uptunning.getText().equals("Consumed"))
        {
            temp = "TRUE";
        }else if(txt_uptunning.getText().equals("FREE"))
        {
            temp = "FALSE";
        }
         
         
         
       // str=txt_tunning.getText();
        if(temp.equals("FALSE"))
        {
           txt_uptunning.setText("Consumed");
           txt_uptunning.setBackground(Color.red);
           temp = "TRUE";
            Connection con = getConnection();
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET Tunning = ? WHERE cus_ID = ?");
           ps.setString(1, temp);
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
          // System.out.println(i);
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,"Tunning:"+ex);
            }
       
        }else if(temp.equals("TRUE"))
        {
            txt_uptunning.setText("FREE");
            txt_uptunning.setBackground(Color.GREEN);
            temp = "FALSE";
            Connection con = getConnection();
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET Tunning = ? WHERE cus_ID = ?");
           ps.setString(1, temp);
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
         //  System.out.println(i);
            }catch(Exception ex)
            {
               JOptionPane.showMessageDialog(null,"Tunning:"+ex);
            }
       
        }
       // tbl_data.repaint();
         Show_Products_In_JTable();
        
        
    }//GEN-LAST:event_btn_chg_tunning1ActionPerformed

    private void btn_chg_repair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chg_repair1ActionPerformed
       
             String str=null;
         
           String temp=null;
        
        if(txt_uprepair.getText().equals("Consumed"))
        {
            temp = "TRUE";
        }else if(txt_uprepair.getText().equals("FREE"))
        {
            temp = "FALSE";
        }
         
       // str=txt_repair.getText();
        if(temp.equals("FALSE"))
        {
           txt_uprepair.setText("Consumed");
           txt_uprepair.setBackground(Color.red);
           temp = "TRUE";
           
            Connection con = getConnection();
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET Repair = ? WHERE cus_ID = ?");
           ps.setString(1, temp);
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
          // System.out.println(i);
            }catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(null,"Repair:"+ex);
            }
       
        }else if(temp.equals("TRUE"))
        {
            txt_uprepair.setText("FREE");
            txt_uprepair.setBackground(Color.GREEN);
            temp = "FALSE";
            Connection con = getConnection();
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET Repair = ? WHERE cus_ID = ?");
           ps.setString(1, temp);
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
         //  System.out.println(i);
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,"Repair:"+ex);
            }
       
        }
     //   tbl_data.repaint();
         Show_Products_In_JTable();
        
    }//GEN-LAST:event_btn_chg_repair1ActionPerformed

    private void btn_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear1ActionPerformed

       txt_upid.setText(null);
       txt_ups.setText(null);
       txt_upname.setText(null);
       txt_upoilchange.setText(null);
       txt_upoilchange.setBackground(null);
       txt_uptunning.setText(null);
       txt_uptunning.setBackground(null);
       txt_uprepair.setText(null);
       txt_uprepair.setBackground(null);
        
    }//GEN-LAST:event_btn_clear1ActionPerformed

    private void btn_chg_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chg_name1ActionPerformed
     
         Connection con = getConnection();
         if(txt_upname.getText().length()==0)
         {
             JOptionPane.showMessageDialog(null, "Enter Name For Updating Customer Name");
         }
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET cus_Name = ? WHERE cus_ID = ?");
           ps.setString(1, txt_upname.getText());
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
          // System.out.println(i);
            }catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(null,"Name Change:"+ex);
            }
         Show_Products_In_JTable();
    }//GEN-LAST:event_btn_chg_name1ActionPerformed

    private void txt_upidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_upidActionPerformed

    private void btn_chg_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chg_idActionPerformed
       
         Connection con = getConnection();
         
         if(txt_upid.getText().length()==0)
         {
             JOptionPane.showMessageDialog(null, "Enter ID for Updating Customer ID");
         }else
         {
            try{
           PreparedStatement ps = con.prepareStatement("UPDATE Company SET cus_ID = ? WHERE cus_ID = ?");
           ps.setString(1, txt_upid.getText());
           ps.setString(2, txt_ups.getText());
          int i = ps.executeUpdate();
          // System.out.println(i);
            }catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(null,"Name Change:"+ex);
            }
         }
         Show_Products_In_JTable();
    }//GEN-LAST:event_btn_chg_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_chg_id;
    private javax.swing.JButton btn_chg_name1;
    private javax.swing.JButton btn_chg_oil1;
    private javax.swing.JButton btn_chg_repair1;
    private javax.swing.JButton btn_chg_tunning1;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clear1;
    private javax.swing.JButton btn_clr;
    private javax.swing.JButton btn_delclear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_upsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_addid;
    private javax.swing.JLabel lbl_addname;
    private javax.swing.JLabel lbl_delid;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_oilChange;
    private javax.swing.JLabel lbl_oilChange1;
    private javax.swing.JLabel lbl_repair;
    private javax.swing.JLabel lbl_repair1;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_search1;
    private javax.swing.JLabel lbl_tuning;
    private javax.swing.JLabel lbl_tuning1;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_addid;
    private javax.swing.JTextField txt_addname;
    private javax.swing.JTextField txt_delid;
    private javax.swing.JTextField txt_delname;
    private javax.swing.JTextField txt_deloil;
    private javax.swing.JTextField txt_delrep;
    private javax.swing.JTextField txt_deltun;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_foilchange;
    private javax.swing.JTextField txt_frepair;
    private javax.swing.JTextField txt_ftunning;
    private javax.swing.JTextField txt_s;
    private javax.swing.JTextField txt_upid;
    private javax.swing.JTextField txt_upname;
    private javax.swing.JTextField txt_upoilchange;
    private javax.swing.JTextField txt_uprepair;
    private javax.swing.JTextField txt_ups;
    private javax.swing.JTextField txt_uptunning;
    // End of variables declaration//GEN-END:variables
}
